baseURL = "http://etiennebouteille.com/"
languageCode = "en-us"
title = "Etienne Bouteille"
pluralizeListTitles = false

[[menu.main]]
    identifier = "2018"
    name = "2018"
    url = "/2018/"
    weight = 1

[[menu.main]]
    identifier = "2017"
    name = "2017"
    url = "/2017/"
    weight = 2

[[menu.main]]
    identifier = "2016"
    name = "2016"
    url = "/2016/"
    weight = 3