baseURL = "https://eloquent-lovelace-d848bf.netlify.com/"
languageCode = "en-us"
title = "Morgane Siau"
pluralizeListTitles = false

[[menu.main]]
    identifier = "Animations"
    name = "Animations"
    url = "/Animations"
    weight = 1

[[menu.main]]
    identifier = "Design d'objets"
    name = "Design d'objets"
    url = "/design_dobjet/"
    weight = 2

[[menu.main]]
    identifier = "Illustrations"
    name = "Illustrations"
    url = "/illustrations/"
    weight = 3